services:
  php:
    build:
      context: './docker/php'
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG:-client_host=host.docker.internal}
    depends_on:
      - db

  db:
    image: mysql:8.3
    restart: always
    container_name: admira_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-admira}
      MYSQL_USER: ${MYSQL_USER:-admira}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admira_pass}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
